name: speech-pipeline
channels:
  - nvidia          # for the CUDA runtime (via pytorch-cuda)
  - pytorch         # for PyTorch, torchvision, torchaudio
  - conda-forge     # for pandas, matplotlib, OpenCV, and other conda‑friendly deps
  - defaults

dependencies:
  # Base Python
  - python=3.10

  # Conda‑managed CUDA + PyTorch stack
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1

  # Data/frame + plotting libraries
  - pandas
  - matplotlib

  # Use pip for the rest of the stack
  - pip
  - pip:
    - tensorflow==2.12           # for DeepFace
    - opencv-python              # cv2
    - deepface                   # facial emotion
    - whisperx                   # WhisperX transcription + diarization
    - pyannote.audio             # speaker diarization
    - transformers               # text emotion with HuggingFace
    - speechbrain                # audio emotion
    - gradio                     # UI
    - yt-dlp                     # YouTube downloads