# Generated by Copilot
"""
Defines domain-specific exception classes for the transmotify application.
"""


class TransmotifyError(Exception):
    """Base exception class for all application-specific errors."""
    pass


class PipelineStageError(TransmotifyError):
    """Exception raised when an error occurs within a pipeline stage."""
    pass


class ConfigurationError(TransmotifyError):
    """Exception raised when there's an issue with configuration."""
    pass


class InputDataError(TransmotifyError):
    """Exception raised when there's an issue with input data."""
    pass


class ProcessingError(TransmotifyError):
    """Exception raised when there's an error during processing."""
    pass


class ResourceAccessError(TransmotifyError):
    """Exception raised when there's an issue accessing a resource."""
    pass
