name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.0.0

      - name: Setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest rich

      - name: Run unit & integration tests
        run: pytest -q
